import React from "react";
import { Image } from "react-native";

const images = {
  EMPLOYEE_SR: require("../../../public/images/employee-icon.png"),
  PDF: require("../../../public/images/pdf.png"),
  PUBLISH: require("../../../public/images/publish.png"),
  UNPUBLISH: require("../../../public/images/unpublish.png"),
  DELETE_PRODUCT: require("../../../public/images/delete.png"),
  RIGHT_ARROW: require("../../../public/images/arrow_right_white.png"),
  RIGHT_ARROW_BLACK: require("../../../public/images/arrow_right_black.png"),
  COLORED_MANUFACTURER: require("../../../public/images/manufacturer_colored.png"),
  COLORED_SUPPLIER: require("../../../public/images/supplier_colored.png"),
  COLORED_RETAILER: require("../../../public/images/retailer_colored.png"),
  CAMERA: require("../../../public/images/camera.png"),
  GO_BACK: require("../../../public/images/back_white_no_padding.png"),
  MENU: require("../../../public/images/menu.png"),
  BOOKING: require("../../../public/images/booking.png"),
  BOOKING_ALTERNATE: require("../../../public/images/booking_white.png"),
  LOG_OUT: require("../../../public/images/log_out.png"),
  ADD: require("../../../public/images/add_red.png"),
  ORDER: require("../../../public/images/order.png"),
  ORDER_ALTERNATE: require("../../../public/images/order_white.png"),
  PRODUCT: require("../../../public/images/product.png"),
  PRODUCT_ALTERNATE: require("../../../public/images/product_white.png"),
  SEARCH: require("../../../public/images/search_black_no_padding.png"),
  SETTINGS: require("../../../public/images/settings.png"),
  SETTINGS_ALTERNATE: require("../../../public/images/settings_white.png"),
  ARROW_RIGHT: require("../../../public/images/keyboard_arrow_right.png"),
  BUSINESS: require("../../../public/images/business.png"),
  REFERRAL: require("../../../public/images/referral.png"),
  PASSWORD: require("../../../public/images/change_password.png"),
  HELP: require("../../../public/images/help.png"),
  TERM: require("../../../public/images/terms.png"),
  PRIVACY: require("../../../public/images/privacy_policy.png"),
  PROFILE: require("../../../public/images/my_profile.png"),
  VERSION: require("../../../public/images/version.png"),
  LOGOUT: require("../../../public/images/logout.png"),
  BRAND: require("../../../public/images/brand.png"),
  MANUFACTURER: require("../../../public/images/Manufacturer.png"),
  HAWKER: require("../../../public/images/center.png"),
  ENTERTAINMENT: require("../../../public/images/ent.png"),
  HOTEL: require("../../../public/images/hotel.png"),
  MART: require("../../../public/images/mart-mini.png"),
  OFFICE: require("../../../public/images/officed.png"),
  RESTAURANT: require("../../../public/images/rest.png"),
  WHOLESALER: require("../../../public/images/wholesaler.png"),
  DISTRIBUTOR: require("../../../public/images/distributor.png"),
  SUPERMART: require("../../../public/images/super-mart.png"),
  BARCODE: require("../../../public/images/barcode.png"),
  DISCOUNT_RED: require("../../../public/images/discount_red.png"),
  OFFER: require("../../../public/images/offer.png"),
  PACK: require("../../../public/images/pack.png"),
  VARIANT: require("../../../public/images/variant.png"),
  EDIT: require("../../../public/images/edit_white.png"),
  DONE: require("../../../public/images/done_white.png"),
  ADD_ALTERNATE: require("../../../public/images/add_white.png"),
  GALLERY: require("../../../public/images/gallery.png"),
  DONEBLACK: require("../../../public/images/done_black_no_padding.png"),
  ARROW_UP: require("../../../public/images/arrow_up.png"),
  ARROW_DOWN: require("../../../public/images/arrow_down.png"),
  REFERRAL_COLOR: require("../../../public/images/referral_colored.png"),
  CROSS: require("../../../public/images/close_black.png"),
  EKKBAZ: require("../../../public/images/ekkbaz_logo.png"),
  CALENDER: require("../../../public/images/calender.png"),
  CUSTOMER: require("../../../public/images/customer.png"),
  SUPPLIER: require("../../../public/images/supplier.png"),
  INVENTORY: require("../../../public/images/inventory.png"),
  PACKAGE: require("../../../public/images/pack.png"),
  PRODUCT_LINE: require("../../../public/images/price.png"),
  CATEGORY: require("../../../public/images/price.png"),
  SUB_CATEGORY: require("../../../public/images/price.png"),
  ARROW_RIGHT_ALTERNATE: require("../../../public/images/arrow_right_white.png"),
  CUSTOMER_ALTERNATE: require("../../../public/images/customer_white.png"),
  CHAT: require("../../../public/images/chat.png"),
  LOCATION: require("../../../public/images/location.png"),
  PHONE: require("../../../public/images/phone.png"),
  HOME: require("../../../public/images/home.png"),
  EMPLOYEE: require("../../../public/images/employee.png"),
  SUPPLIER_ALTERNATE: require("../../../public/images/supplier_white.png"),
  SUPPLIER_RED: require("../../../public/images/supplier_red.png"),
  CUSTOMER_RED: require("../../../public/images/customer_red.png"),
  BUSINESS_RED: require("../../../public/images/business_red.png"),
  QRCODE: require("../../../public/images/qrcode.png"),
  HOME_ALTERNATE: require("../../../public/images/home_white.png"),
  DELIVERED_ALTERNATE: require("../../../public/images/delivered_white.png"),
  PAID_ALTERNATE: require("../../../public/images/paid_white.png"),
  CROSS_ALTERNATE: require("../../../public/images/close_white_padding.png"),
  CHAT_ALTERNATE: require("../../../public/images/chat_white.png"),
  DISCOVER_ALTERNATE: require("../../../public/images/discover_white.png"),
  DISCOVER: require("../../../public/images/discover.png"),
  BARCODE_ALTERNATE: require("../../../public/images/barcode_white.png"),
  NOTIFICATION_ALTERNATE: require("../../../public/images/notification_white.png"),
  VARIANT_RED: require("../../../public/images/variant_red.png"),
  PACK_RED: require("../../../public/images/pack_red.png"),
  OFFER_RED: require("../../../public/images/offer_red.png"),
  DISCOUNT: require("../../../public/images/discount.png"),
  DISCOUNT_ALTERNATE: require("../../../public/images/discount_white.png"),
  INVENTORY_ALTERNATE: require("../../../public/images/inventory_white.png"),
  EMPLOYEE_ALTERNATE: require("../../../public/images/employee_white.png"),
  BRANCH_RED: require("../../../public/images/business_red.png"),
  BRANCH: require("../../../public/images/branch.png"),
  TROPHY: require("../../../public/images/trophy.png"),
  CHAT_REPLY: require("../../../public/images/chat_reply.png"),
  CHAT_ATTACHMENT: require("../../../public/images/attachment.png"),
  CHAT_CAMERA: require("../../../public/images/chat_camera.png"),
  CHAT_PRIVATE: require("../../../public/images/private_chat.png"),
  CHAT_GROUP: require("../../../public/images/group_chat.png"),
  VERIFIED: require("../../../public/images/verified.png"),
  LANGUAGE: require("../../../public/images/language.png"),
  EYE: require("../../../public/images/eye.png"),
  NO_RECORD: require("../../../public/images/no_record.png"),
  DEFAULT_IMAGE: require("../../../public/images/product_background.png"),
  DOWNLOAD: require("../../../public/images/download.png")
};

const CustomImage = ({
  type,
  styles = { height: 25, width: 25 },
  dimensions = null,
  source = null
}) => {
  // console.log(type);
  let newHeight = dimensions
    ? Math.round(dimensions.originalHeight / dimensions.originalWidth * dimensions.newWidth)
    : 0;
  // if (dimensions) console.warn(newHeight, dimensions.newWidth);
  return (
    <Image
      style={[styles, dimensions ? { height: newHeight, width: dimensions.newWidth } : null]}
      source={source ? source : images[type]}
    />
  );
};

export default CustomImage;
